import { PublicLayout } from "@/components/layout/PublicLayout";
import { Card, CardContent } from "@/components/ui/card";
import {
  Brain,
  Map,
  Target,
  Compass,
  TrendingUp,
  Shield,
  Lightbulb,
  CheckSquare,
  Zap,
} from "lucide-react";

const features = [
  { icon: Brain, title: "AI-Powered Roadmaps", desc: "Get personalized semester-wise roadmaps generated by AI, tailored to your branch, interests, and career goals." },
  { icon: Map, title: "Domain Exploration", desc: "Try 5–14 day structured trials in Web Dev, Data Science, AI/ML, and more before choosing your path." },
  { icon: Target, title: "Placement Planner", desc: "Company-specific preparation, mock interviews, and readiness scores to ace your placements." },
  { icon: Compass, title: "Internship Planner", desc: "Track internship windows, build skills, and ensure resume readiness semester by semester." },
  { icon: TrendingUp, title: "Progress Tracking", desc: "Visual dashboards with skill growth charts, streak tracking, and milestone celebrations." },
  { icon: Shield, title: "Communication Skills", desc: "Weekly tasks to improve English, presentation skills, and interview readiness." },
  { icon: Lightbulb, title: "AI Mentor Insights", desc: "Receive personalized tips on career direction, focus areas, and skill gaps from your AI mentor." },
  { icon: CheckSquare, title: "Task Management", desc: "Organized daily and weekly tasks with priority flags, domain tags, and completion tracking." },
  { icon: Zap, title: "Smart Recommendations", desc: "Focus Now and Avoid Now flags help you prioritize what matters most at each stage." },
];

export default function FeaturesPage() {
  return (
    <PublicLayout>
      <section className="py-20">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <h1 className="text-4xl font-bold">Features</h1>
            <p className="mt-4 text-lg text-muted-foreground">
              Everything you need to navigate your engineering journey with confidence.
            </p>
          </div>
          <div className="mt-16 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {features.map((f) => (
              <Card key={f.title} className="border-border/50 transition-colors hover:border-primary/30">
                <CardContent className="p-6">
                  <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10">
                    <f.icon className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="text-lg font-semibold">{f.title}</h3>
                  <p className="mt-2 text-sm text-muted-foreground">{f.desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>
    </PublicLayout>
  );
}
