import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { PublicLayout } from "@/components/layout/PublicLayout";
import {
  Brain,
  Map,
  Target,
  Compass,
  CheckCircle,
  TrendingUp,
  ArrowRight,
  Star,
  Zap,
  Shield,
  Users,
  GraduationCap,
} from "lucide-react";
import { motion } from "framer-motion";

const features = [
  { icon: Brain, title: "AI-Powered Roadmaps", desc: "Personalized semester-wise learning paths generated by AI based on your goals." },
  { icon: Map, title: "Domain Exploration", desc: "Try different engineering domains with structured trial periods before committing." },
  { icon: Target, title: "Placement Planner", desc: "Phase-wise preparation with company-specific prep and mock interviews." },
  { icon: Compass, title: "Internship Planner", desc: "Track internship windows, build resume readiness, and stay ahead." },
  { icon: TrendingUp, title: "Progress Tracking", desc: "Visual dashboards showing skill growth, streak tracking, and milestones." },
  { icon: Shield, title: "Communication Skills", desc: "Weekly tasks to improve English, interview skills, and presentation ability." },
];

const steps = [
  { num: "01", title: "Sign Up & Onboard", desc: "Tell us your branch, year, interests, and career goals." },
  { num: "02", title: "Get Your Roadmap", desc: "AI generates a personalized semester-wise learning roadmap." },
  { num: "03", title: "Explore & Learn", desc: "Try domains, complete tasks, and track your progress daily." },
  { num: "04", title: "Achieve Your Goal", desc: "Land your dream internship or placement with confidence." },
];

const testimonials = [
  { name: "Priya S.", role: "3rd Year, CSE", quote: "EngiPath helped me find my passion in data science and land a summer internship!", rating: 5 },
  { name: "Rahul M.", role: "2nd Year, ECE", quote: "The roadmap kept me focused. I went from confused to confident in one semester.", rating: 5 },
  { name: "Ananya K.", role: "4th Year, IT", quote: "The placement planner was a game-changer. I cracked interviews at 3 companies!", rating: 5 },
];

const fadeUp = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0 },
};

export default function LandingPage() {
  return (
    <PublicLayout>
      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/10 via-transparent to-accent/10" />
        <div className="container relative py-24 md:py-32">
          <motion.div
            initial="hidden"
            animate="visible"
            variants={fadeUp}
            transition={{ duration: 0.6 }}
            className="mx-auto max-w-3xl text-center"
          >
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border bg-card px-4 py-1.5 text-sm text-muted-foreground">
              <Zap className="h-4 w-4 text-primary" />
              AI-Powered Engineering Roadmaps
            </div>
            <h1 className="text-4xl font-bold tracking-tight md:text-6xl">
              Your Engineering Career,{" "}
              <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
                Mapped by AI
              </span>
            </h1>
            <p className="mt-6 text-lg text-muted-foreground md:text-xl">
              Personalized roadmaps, domain exploration, placement prep, and AI mentorship — 
              everything engineering students need to go from Day 1 to Dream Job.
            </p>
            <div className="mt-8 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
              <Button size="lg" asChild className="gap-2">
                <Link to="/register">
                  Get Started Free <ArrowRight className="h-4 w-4" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" asChild>
                <Link to="/how-it-works">See How It Works</Link>
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="border-t bg-card/50 py-20">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold">Everything You Need to Succeed</h2>
            <p className="mt-3 text-muted-foreground">
              From roadmap generation to placement preparation, EngiPath AI covers your entire engineering journey.
            </p>
          </div>
          <div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {features.map((f, i) => (
              <motion.div
                key={f.title}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={fadeUp}
                transition={{ duration: 0.4, delay: i * 0.1 }}
              >
                <Card className="h-full border-border/50 bg-card transition-colors hover:border-primary/30">
                  <CardContent className="p-6">
                    <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                      <f.icon className="h-5 w-5 text-primary" />
                    </div>
                    <h3 className="text-lg font-semibold">{f.title}</h3>
                    <p className="mt-2 text-sm text-muted-foreground">{f.desc}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How it Works */}
      <section className="py-20">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold">How It Works</h2>
            <p className="mt-3 text-muted-foreground">Four simple steps to transform your engineering journey.</p>
          </div>
          <div className="mt-12 grid gap-8 md:grid-cols-2 lg:grid-cols-4">
            {steps.map((s, i) => (
              <motion.div
                key={s.num}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={fadeUp}
                transition={{ duration: 0.4, delay: i * 0.15 }}
                className="text-center"
              >
                <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-primary text-xl font-bold text-primary-foreground">
                  {s.num}
                </div>
                <h3 className="text-lg font-semibold">{s.title}</h3>
                <p className="mt-2 text-sm text-muted-foreground">{s.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="border-t bg-card/50 py-20">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold">What Students Say</h2>
            <p className="mt-3 text-muted-foreground">Join thousands of engineering students already on their path.</p>
          </div>
          <div className="mt-12 grid gap-6 md:grid-cols-3">
            {testimonials.map((t, i) => (
              <Card key={i} className="border-border/50">
                <CardContent className="p-6">
                  <div className="mb-3 flex gap-1">
                    {Array.from({ length: t.rating }).map((_, j) => (
                      <Star key={j} className="h-4 w-4 fill-warning text-warning" />
                    ))}
                  </div>
                  <p className="text-sm italic text-muted-foreground">"{t.quote}"</p>
                  <div className="mt-4 flex items-center gap-2">
                    <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 text-xs font-semibold text-primary">
                      {t.name[0]}
                    </div>
                    <div>
                      <p className="text-sm font-medium">{t.name}</p>
                      <p className="text-xs text-muted-foreground">{t.role}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Preview */}
      <section className="py-20">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold">Simple, Transparent Pricing</h2>
            <p className="mt-3 text-muted-foreground">Start free. Upgrade when you're ready.</p>
          </div>
          <div className="mt-12 grid gap-6 md:grid-cols-3">
            {[
              { name: "Free", price: "₹0", desc: "Get started", features: ["Basic roadmap", "3 domain trials", "Progress tracking", "Community access"] },
              { name: "Pro", price: "₹499/mo", desc: "Most popular", features: ["AI-powered roadmap", "Unlimited domain trials", "Placement planner", "AI mentor insights", "Priority support"], popular: true },
              { name: "Premium", price: "₹999/mo", desc: "For serious achievers", features: ["Everything in Pro", "1-on-1 AI mentorship", "Resume review", "Mock interviews", "Company-specific prep"] },
            ].map((plan) => (
              <Card
                key={plan.name}
                className={`relative ${plan.popular ? "border-primary shadow-lg shadow-primary/10" : "border-border/50"}`}
              >
                {plan.popular && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-primary px-3 py-1 text-xs font-semibold text-primary-foreground">
                    Most Popular
                  </div>
                )}
                <CardContent className="p-6">
                  <h3 className="text-lg font-semibold">{plan.name}</h3>
                  <p className="text-sm text-muted-foreground">{plan.desc}</p>
                  <p className="mt-4 text-3xl font-bold">{plan.price}</p>
                  <ul className="mt-6 space-y-2">
                    {plan.features.map((f) => (
                      <li key={f} className="flex items-center gap-2 text-sm">
                        <CheckCircle className="h-4 w-4 text-secondary" />
                        {f}
                      </li>
                    ))}
                  </ul>
                  <Button className="mt-6 w-full" variant={plan.popular ? "default" : "outline"} asChild>
                    <Link to="/register">Get Started</Link>
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t bg-gradient-to-r from-primary/10 to-accent/10 py-20">
        <div className="container text-center">
          <GraduationCap className="mx-auto h-12 w-12 text-primary" />
          <h2 className="mt-4 text-3xl font-bold">Ready to Start Your Journey?</h2>
          <p className="mx-auto mt-3 max-w-xl text-muted-foreground">
            Join thousands of engineering students who are building their careers with AI-powered guidance.
          </p>
          <div className="mt-8 flex justify-center gap-4">
            <Button size="lg" asChild>
              <Link to="/register">Create Free Account</Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link to="/contact">Contact Us</Link>
            </Button>
          </div>
        </div>
      </section>
    </PublicLayout>
  );
}
